# WARNING: Do not deploy this configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly.  

version: "3"

services:

  # example01       
  example01:
    build: ./example01
    hostname: example01
    container_name: example01
    restart: unless-stopped
    networks:
      example01-net:

#Create internal link network for Containers
networks:
  example01-net:

#Create Volumes for persistent Storage
#volumes:
#  example01Log:
#  example01Data:
